apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -prod

replicas:
  - name: capstone-app
    count: 3

images:
  - name: app-image
    newName: ghcr.io/your-org/your-repo
    newTag: stable
