apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: app
        image: ghcr.io/your-org/your-repo:changeme
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet: { path: /healthz, port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: 3000 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
