apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devsecops
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - prometheus-rbac.yaml

images:
  - name: app-image
    newName: ghcr.io/your-org/your-repo
    newTag: latest
