apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:dev, applications, get, default/*, allow
    p, role:dev, applications, sync, default/*, allow
    g, dev-user, role:dev